version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leetbrawl
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  judge0:
    image: judge0/judge0:1.13.0
    environment:
      - JUDGE0_DATABASE_URL=postgresql://user:password@postgres:5432/leetbrawl
      - REDIS_URL=redis://redis:6379
    ports:
      - '2358:2358'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  pgdata: 